name: "Publish ECR"

on:
  push:
    branches:
      - master

jobs:
  # Builds a new container image, and pushes it on every commit to the repository
  # Also pushes a tag called "latest" to track the lates commit

  build_docker_image:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t ppe
          docker tag ppe 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kand2035:$rev
          docker tag ppe 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kand2035:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kand2035:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kand2035:latest